zuul:
  routes:
    auth:
      path: /auth/**
      url: https://greenapp-auth-service.herokuapp.com/auth
    task:
      path: /task-provider/**
      url: https://greenapp-task-provider.herokuapp.com/
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
    semaphore:
      max-semaphores: 500
    sensitive-headers: true

jwt:
  secret: ortam
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  eureka:
    enabled: false


server:
  port: 8999
